"use strict";

/*
 * Коды комнат для всех мультиплеерных игр: СЛОВО + две цифры 2–9 («PANDA47», «SKIBIDI82»).
 * Читается вслух, не перебирается за разумное время (защита от перебора — lib/net.js, createGuessLimiter).
 * Слова: латиница, 3–9 букв — код целиком (≤ 11 знаков) должен влезать в поле ввода (maxlength 12).
 * Список общий для всех игр; хочешь добавить слово — добавь сюда, а не в сервер игры.
 */

const crypto = require("crypto");

const ROOM_WORDS = (
  "DOGE PEPE KEKW SIGMA SKIBIDI RIZZ GIGACHAD BASED CRINGE YEET BONK STONKS HODL MOON NPC MEWING SUS " +
  "AMOGUS NYAN SHREK CHEEMS BORSCH BABUSHKA KOLOBOK PELMENI CHEBUREK SHAWARMA BUBLIK SEMECHKI GOPNIK " +
  "BAYAN KRUTO CHILL VIBE FLEX YOLO SWAG LOL OMG BRUH BOBR CAPYBARA GOOSE HAMSTER PIGEON NOODLE POTATO " +
  "PICKLE BANANA WAFFLE MEME TROLL NOOB PRO CLUTCH LAG PING BUFF NERF LOOT BOSS SPAWN RESPAWN CAMPER " +
  "TILT SWEAT HYPE COPIUM HOPIUM DELULU SLAY BOOMER ZOOMER KAREN CHAD WOJAK GRUMPY CATJAM BONGO DOOMER " +
  "FRIEND GIGA TURBO UWU OWO KAWAII SENPAI MOGGING AURA PLOT DRIP SNACK CRUMB BAGUETTE CROISSANT KEBAB " +
  "SUSHI RAMEN PIZZA TACO BURRITO DONER LAVASH KHINKALI PLOV OKROSHKA SELEDKA SALO BLINI VAREZHKI " +
  "SYRNIKI TAPOK BALALAIKA VODKA SAMOVAR SHAPKA USHANKA BID LOT GAVEL HAMMER SOLD DEAL OFFER PRICE " +
  "BARGAIN BUYER DEALER BROKER TOKEN COIN DOLLAR CASH VAULT SAFE GOLD SILVER BRONZE RUBY PEARL JEWEL " +
  "AMBER JADE OPAL CROWN TIARA SCEPTER THRONE VASE STATUE CANVAS EASEL ANTIQUE RELIC TROPHY MEDAL " +
  "STAMP VINYL RECORD GUITAR PIANO CELLO BANJO VIOLIN DRUM TANGO DISCO JAZZ OPERA PANDA OTTER LLAMA " +
  "ZEBRA FALCON RAVEN EAGLE BISON BADGER GECKO COBRA SHARK WHALE MANGO LEMON PEACH COMET ORBIT PLANET " +
  "NOVA LUNA CASTLE TOWER PALACE HARBOR CACTUS DUCK QUACK RIVER CREEK BROOK RAPIDS RAFT CANOE KAYAK " +
  "PADDLE OAR LILY LOTUS REED WILLOW FROG TOAD HERON STORK SWAN BEAVER TROUT SALMON PIKE CARP NEWT " +
  "PEBBLE BOULDER DELTA LAGOON MARSH BUBBLE SPLASH RIPPLE WAVE ISLAND MEADOW FERN MOSS PINE CEDAR " +
  "MAPLE MAGNET SALSA DONUT MUFFIN PRETZEL NACHO PEPPER BRIDGE CELL BARS JAIL KEY LOCK GUARD ESCAPE " +
  "TUNNEL SHOVEL LADDER ROPE SPOON QUIZ BRAIN GENIUS ANSWER RIDDLE PUZZLE CLUE MYSTERY ROBOT BRAVO " +
  "PUFFIN TOUCAN PARROT SOLAR STORM OCEAN CORAL CANYON FOREST WASABI BOMB BOOM FUSE SPARK FLASH BANG " +
  "POP ZAP KAPOW WHAM TNT DYNAMO ROCKET NEON LASER PIXEL RUMBA BLUES VALLEY CHILI FAIR CROWD HERD " +
  "FLOCK PACK TEAM PULL TUG KNOT FLAG MUD PUDDLE BARN HAY CART PONY GOAT SHEEP MOOSE DONKEY TURKEY " +
  "CRICKET BEETLE ALDER PLUM CHERRY APPLE PEAR MELON GRAPE BERRY CANDY PIE CAKE BUN JAM HONEY TOAST " +
  "SOUP STEW BREAD CHEESE POLKA WALTZ FLUTE HORN TUBA BELL EMBER SUN CLOUD BREEZE FROST SNOW RAIN MIST " +
  "DUNE MESA REEF COVE ISLE PEAK GLEN FIB LIAR TRUTH FAKE HOAX BLUFF RUMOR NEWS PRESS INK SCOOP GOSSIP " +
  "SURF TIDE DIAL NEEDLE RADAR SONAR ECHO PULSE SIGNAL TUNER METER GAUGE ARC FLOE ICE GLACIER IGLOO " +
  "BERG POLAR ARCTIC AURORA BLIZZARD SLEET HAIL WALRUS SEAL ORCA NARWHAL PENGUIN KRILL HERRING SARDINE " +
  "TUNA SQUID YETI HUSKY SLED SKATE SKI MITTEN SCARF BEANIE COCOA CANDLE FJORD TUNDRA JOKE PUNCH QUIP " +
  "GAG WIT PUN SASS ZING MIC STAGE ENCORE ACE BANK BET BLACK CASINO CHIP CLUB DIAMOND DICE DOUBLE " +
  "EIGHT EMERALD FORTUNE GRAND JACK JOKER KING LUCKY MAGIC MARBLE MONACO NOIR ONYX QUEEN RED ROUGE " +
  "ROYAL SPADE SPIN STAR TIGER TOPAZ VEGAS VELVET WHEEL ZERO BRASS COPPER WALNUT COBALT SILK DENIM " +
  "APRICOT COCONUT FIG LIME OLIVE ORANGE PAPAYA POMELO RAISIN CASHEW HAZELNUT PECAN PISTACHIO ACORN " +
  "CHESTNUT CELERY CORN CUCUMBER GARLIC LEEK LETTUCE MUSHROOM RADISH SPINACH TOMATO TURNIP PUMPKIN " +
  "BEET CABBAGE BAGEL BISCUIT BROWNIE COOKIE CREPE CUPCAKE CUSTARD FUDGE GELATO JELLY LATTE MOCHA " +
  "PANCAKE PASTA PUDDING SALAD SANDWICH SYRUP TOFFEE TRUFFLE YOGURT NUGGET FRIES BURGER HOTDOG POPCORN " +
  "CURRY RISOTTO FALAFEL HUMMUS GYOZA TEMPURA UDON TEA CIDER SODA ANTELOPE BAT BEAR CAMEL CAT CHEETAH " +
  "CLAM CRAB CROW DOLPHIN DRAGON ELEPHANT FERRET FLAMINGO FOX GAZELLE GORILLA HYENA IGUANA KANGAROO " +
  "KOALA LEMUR LEOPARD LION LOBSTER LYNX MINK MOLE MONKEY MOUSE OCTOPUS OYSTER PHOENIX PUMA RABBIT " +
  "RHINO ROOSTER SLOTH SNAIL SNAKE SPARROW TURTLE WASP WEASEL WOLF WOMBAT ZEBU BUNNY FAWN GOSLING " +
  "MARMOT GOPHER CHIPMUNK MANATEE PELICAN CONDOR KESTREL OSPREY ROBIN SWALLOW WREN FINCH AUTUMN " +
  "DRIZZLE DUSK FOG GALE HAZE RAINBOW SPRING SUMMER SUNSET WINTER TYPHOON HURRICANE CYCLONE CAVE " +
  "DESERT HILL JUNGLE LAKE MOUNTAIN OASIS PLAIN RIDGE SHORE STEPPE SWAMP TAIGA VOLCANO ASTEROID GALAXY " +
  "NEBULA PLUTO VENUS SATURN NEPTUNE URANUS COSMOS PULSAR QUASAR ZENITH ACCORDION BAGPIPE BASS BONGOS " +
  "BUGLE CLARINET DULCIMER HARP KAZOO LUTE MARIMBA ORGAN PICCOLO SAX SITAR UKULELE XYLOPHONE ZITHER " +
  "SYNTH BEAT RIFF MELODY CHORUS RHYTHM TEMPO ANTHEM GROOVE FUNK ROCK TECHNO REGGAE BOLERO FLAMENCO " +
  "ANCHOR BUOY DOCK FERRY GALLEON HELM KEEL MAST SAIL SAILOR SHIP SUB YACHT SKIFF TUGBOAT TREASURE BUS " +
  "KART SCOOTER TAXI TRAIN TRAM TRUCK VAN WAGON TRACTOR GLIDER BLIMP JET PLANE BASKET BOWL BROOM CHAIR " +
  "COMB CUP GLOVE LAMP LANTERN MIRROR NAPKIN PILLOW PLATE STOOL TOWEL UMBRELLA WINDOW HAT BOOT ARCHER " +
  "BARON CHEF CLOWN DRUID ELF GIANT GNOME HERO JESTER KNIGHT MAGE OGRE PALADIN PIXIE RANGER ROGUE " +
  "SHAMAN TITAN VIKING WIZARD ZOMBIE CYBORG ALIEN GHOST MUMMY SPHINX GRIFFIN KRAKEN HYDRA MERMAID " +
  "CENTAUR BANNER BEACON BRAVE CHAMP CHAPTER CODE CRAFT CREW DUEL FABLE FLAME FORGE GLORY GUILD HONOR " +
  "JOURNEY LEGEND MISSION MYTH NOBLE OMEN ORACLE PORTAL QUEST SAGA SHIELD SPELL TALE VICTORY WARRIOR " +
  "BINGO DARTS DOMINO LUDO POKER TAG HOCKEY POLO JUDO BOXING CURLING BOWLING LASSO TRIVIA CARDS " +
  "MARATHON ATOM CABLE CURSOR DATA FILE HACK ICON LOGIN PROXY ROUTER SPAM TWEET VIRUS WIFI ZIP MODEM " +
  "PLUGIN SCRIPT WIDGET PODCAST STREAM COMEDY DRAMA ACTOR SCENE TRAILER COMIC ANIME MANGA BLUE CRIMSON " +
  "CYAN GREEN INDIGO IVORY LILAC MAGENTA MAROON PINK SCARLET TEAL VIOLET YELLOW AZURE KHAKI JOLLY " +
  "MERRY HAPPY SILLY FUNNY FUZZY BOUNCY SWEET SALTY SNEAKY SLEEPY SPEEDY WILD CHEERY CLEVER COZY CUTE " +
  "DAPPER GENTLE GIDDY HIP NIFTY PROUD SHINY SMOOTH SNAPPY SNUG SPARKY SPUNKY SUPER TIDY WACKY WITTY " +
  "ZANY CLANG CRASH DING DONG GONG OINK POOF SMASH SNAP SPLAT SWOOSH THUD THWACK TWANG VROOM WHOOSH " +
  "WOOF MEOW MOO RIBBIT ATTIC FARM FORT GARDEN GARAGE HUT KIOSK MARKET MILL MUSEUM PARK PLAZA PORCH " +
  "ROOF SCHOOL SHOP STUDIO TENT TOWN VILLAGE YARD FOXTROT INDIA KILO OSCAR PAPA QUEBEC SIERRA VICTOR " +
  "WHISKEY XRAY YANKEE BETA GAMMA OMEGA LONDON ROME TOKYO KYIV ATHENS VIENNA PRAGUE BERLIN MADRID " +
  "LISBON DUBLIN WARSAW BUDAPEST HELSINKI STOCKHOLM MILAN NAPLES DELHI DUBAI HAWAII BALI CRETE MALTA " +
  "IBIZA SAHARA ALPS ANDES URALS DOGGO CHONK SMOL FLOOF BEANS ZOOMIES MOGUS STAN FRFR NOCAP GOATED " +
  "SLAPS BANGER POGGERS POG LULW MONKAS RICKROLL LEROY TROLLFACE DOGGE BOBRIK KOTIK KOTYA GENA " +
  "KARTOSHKA PELMEN OLIVIE TAPKI DEDKA KVAS KEFIR TVOROG SAMSA SHASHLYK CHAKCHAK BARANKA SHCHI PIROG " +
  "PIROZHOK"
).trim().split(/\s+/);
const CODE_DIGITS = "23456789";

// taken(code) → true, если такой код уже занят; перебираем, пока не найдём свободный
function roomCode(taken) {
  for (;;) {
    const code = ROOM_WORDS[crypto.randomInt(ROOM_WORDS.length)] +
      CODE_DIGITS[crypto.randomInt(CODE_DIGITS.length)] + CODE_DIGITS[crypto.randomInt(CODE_DIGITS.length)];
    if (!taken(code)) return code;
  }
}

module.exports = { roomCode, ROOM_WORDS, CODE_DIGITS };
